[package]
name = "framer-bindings"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
godot = { git = "https://github.com/godot-rust/gdext", branch = "master" }
mlua = { version = "0.9.9", features = ["lua54", "vendored"] }
