[package]
name = "frame-server"
version = "0.1.0"
edition = "2021"

[dependencies]
btleplug = { version = "0.11.5", features = ["serde"] }
futures = "0.3.30"
serde = "1.0.210"
tokio = { version = "1.40.0", features = ["full"] }
uuid = "1.10.0"
